### ISSUE TITLE
MAINTAINER open to adding others?

### ISSUE THREAD

**Issue by ekalosak** [zkat/big-brain#100]
Seems like there’s some simple upkeep tasks that could be taken easily off the core maintainer/author’s plate.

I hesitate to be so forward, but a live+useful project like this might stand to benefit from spreading out the maintenance work.

Are there candidate contributors in mind? Has this been considered? Thank you.

**Comment by zkat** [comment]
There's no real candidates right now. I just generally merge things as people send me PRs, but I became a parent a year ago and have had a lot less time for giving attention to more "satellite" projects like this one that aren't my main focus.

I do think there's a lot that can still be done with big-brain, and I'm glad people find it useful, but some help would be nice. I'd like to see someone engage with the project on the regular in a community-member capacity (which lets them do a LOT, except the parts that require handing over significant trust), and have that relationship build up before adding another maintainer more officially.

That is to say, if you want to talk about project direction, share ideas, send PRs, comment on issues, and review incoming PRs, those are all things non-maintainers can do and are always appreciated, and someone who does that regularly and isn't called Jia Tan would probably get onboarded not too soon after doing that for a bit :)

**Comment by ekalosak** [comment]
Congrats :)
And fwiw as long as you do pop in periodically it doesn’t seem like a looming issue.
