### ISSUE TITLE
Bring back weights?

### ISSUE THREAD

**Issue by zkat** [zkat/big-brain#15]
Big Brain used to have [Crystal AI-style `Weight`s](https://igiagkiozis.github.io/CrystalAI/getting-started/#options-and-measures) for its `Consideration`s (now called `Scorer`s). I wasn't sure they would be very useful, but maybe they are? It's worth thinking about bringing _some_ kind of weight system back?

**Comment by will-hart** [comment]
Could this be done with `Evaluator`s? I'm happy to make a PR if that's a good approach. 

Also what are your thoughts on some helper functions for evalutors etc. For instance instead of 

```rust
ProductOfScorers::build(0.8)
    .push(EvaluatingScorer::build(
        scorers::HasAttackTargetScore,
        LinearEvaluator::new_inversed(),
    ))
```

It would be more ergonomic I think to do

```rust
// use big_brain::evaluators::invert;
ProductOfScorers::build(0.8)
    .push(invert(scorers::HasAttackTargetScore))
```

Similarly for weights we could then do

```rust
ProductOfScorers::build(0.8)
    .push(weight(0.5, scorers::HasAttackTargetScore))
```

**Comment by zkat** [comment]
Not quite. I think the right way to implement weights again would be as a regular composite Scorer. I kinda also want a more clear name than "measure" but might go with it anyway because Math Calls It That. So, something like this:

```rust
MeasuredScorer::build()
  .push(scorers::HasAttackTargetScore)
  .push(scorers::HasAmmoScore)
```

And use `WeightedMeasure` as the default measure (you can configure it with `.measure(measures::Chebychev)`).

tbh, this would basically be a fancy and perhaps more "this is what I intended" version of stuff like SumOfScorers that would give a more natural feel for how multiple scorers evaluate together. I'm into it. Would you be up to resurrecting it? I think the implementation is literally just a `SumOfScorers` with the `Measure.calculate(scores)` instead of `scores.sum()`. [This is where measures were removed](https://github.com/zkat/big-brain/commit/e54e8d3788c9416be78328ab50a09e000223b1ae#diff-65c45fca3918ebb36e124d0cc4703d36d844236c0f058af1ba16159776510c94) so you can probably lift that file up as-is.

As far as function utilities: I think if we're going to start adding utilities like this one, we should consider doing it for everything else, too. Additionally, we'd need to have specific modules that would be made available for this, since Rust convention is not to import functions directly, but to use their module (so, `eval::invert(blah)`). Like, in general, I'd like to give more design thought to it because it would definitely be a departure from the current look and feel of Big Brain, and I think it might confuse conventions.

**Comment by will-hart** [comment]
I can have a look I've got a few days off work 👍

My use case for weights was to apply an input weight to a scorer being used by `ProductOfScorers`. I'll play around and have a look, it seems your approach might be applicable to both.

Re the handy utils, yes, I'd see them grouped into a `utils` mod, or maybe even as a separate `big-brain-utils` crate. I think the main benefit for me is it makes defining complex Thinkers much more succinct. I'll build them in "user" code for now and see if I have a bunch of them at the end!
