### ISSUE TITLE
[Suggestion] Use SparseSets for ActionState Component and Benchmarks

### ISSUE THREAD

**Issue by chrisburnor** [zkat/big-brain#29]
Bevy 0.5 introduced `SparseSet` Storage (see [Release Notes](https://bevyengine.org/news/bevy-0-5/#ecs-core-rewrite)) for components with high add/remove volume to avoid .  If I'm understanding, from my (somewhat cursory) reading of the code that `ActionState` probably falls into this category and would probably generate a performance boost if added.

I might be very wrong on the way that ActionState is implemented, but it would be very good to add some benchmarks for performance validation.

**Comment by zkat** [comment]
maybe? I'd take a PR for this :)

**Comment by chrisburnor** [comment]
I'll, see what I can do, though likely the higher priority for me would be #28. If I can figure out the internals enough for that one, I should have enough to implement this one too.
