### ISSUE TITLE
Clean up actions on success/failure

### ISSUE THREAD

**Issue by ndarilek** [zkat/big-brain#34]
Ran into a surprising behavior. I have an `Investigate` action that sets `ActionState::Success` when pathfinding reaches the destination. I then tried to add a component that triggered a wait and `ReturnToPost` action when the timer expired from the `ActionState::Success` match arm.

Unfortunately, I discovered that successful actions don't seem to stop or get cleaned up. They just perpetually run in `ActionState::Success`. So in this case, the handler kept running and re-adding the timer, and my second action didn't run.

Not sure if this is a bug or by design. I removed the action component from the actor myself when the action succeeded. Ideally, I'd have liked it if the action hung around in the success state for long enough for my system to notice, then cleaned up so the actor didn't infinitely run the success state handler.

**Comment by zkat** [comment]
This was fixed as part of #55 :)
