### ISSUE TITLE
Bevy-less Implementation

### ISSUE THREAD

**Issue by hero2002** [zkat/big-brain#46]
so I use macroquad as my rendering framework as i don't need anything more fancy
and now i want to implement ai for my game and I started porting big_brain to just Bevy_Ecs and so far this been easy
and one of the stuff i found is that most entities have children attached to it but from what I saw that isn't needed?

**Comment by zkat** [comment]
The child hierarchy is used for cleanup: https://github.com/zkat/big-brain/blob/main/src/thinker.rs#L162-L173

**Comment by hero2002** [comment]
> The child hierarchy is used for cleanup: https://github.com/zkat/big-brain/blob/main/src/thinker.rs#L162-L173
 I see so I should have something like that in order to clean up
 i guess a vec of childs as components can work and I can query that

**Comment by zkat** [comment]
It's a recursive tree and I found that just using bevy's built-in hierarchy support is better and will play nicer with other things that use that hierarchy.

**Comment by hero2002** [comment]
> It's a recursive tree and I found that just using bevy's built-in hierarchy support is better and will play nicer with other things that use that hierarchy.

I see
I just don't need the whole bevy crate
But still that  can be done with what I said It won't be as nice as the bevy one but It should work right?
