### ISSUE TITLE
Debugging and logging

### ISSUE THREAD

**Issue by will-hart** [zkat/big-brain#53]
I'm finding it a bit tricky to debug thinkers as the `Thinker` is a bit opaque to my code. What I'd love to have is a way to inspect the `Thinker` state for an `Actor`. For instance

 - the result of all the scorers
 - the result of compound scorers
 - the final result of the scorer passed to `when`
 - the action that these scores are related to

At the moment, this requires me instrumenting all the scorer systems, and reimplementing the built-in `Scorers` with additional debug output. However there is still no way to link the scorer back to the action as e.g. `SumOfScorers` isn't aware of the action it relates to.

Is there a recommended way to debug thinkers?

**Comment by zkat** [comment]
It's funny you created this issue now. I'm literally in the process of integrating `tracing` into Thinkers and Actions (and maybe even Scorers), so you'll be able to see how things are getting evaluated, with spanned traces for actions that tell you how their state changed over time, and even a span handle that would let you add to your Action's evaluation span so you can see everything happening in order.

Give me like, a few hours to a day :)

**Comment by will-hart** [comment]
Oh wow 😆 that's good timing!

**Comment by zkat** [comment]
![image](https://user-images.githubusercontent.com/17535/192077383-904b290d-2ec7-4972-aee9-95af9497f34b.png)

This is what I've got so far. What do you think? I'm also talking about it on the Bevy Discord's `#ai` channel.

**Comment by zkat** [comment]
This was done by #55
