### ISSUE TITLE
Require deriving explicitly `ActionBuilder` or `ScorerBuilder`

### ISSUE THREAD

**Issue by cBournhonesque** [zkat/big-brain#62]
I think it would be helpful to require users to derive explicitly `ActionBuilder` and `ScorerBuilder` (and to change all the `impl ActionBuilder` into `ActionBuilder`, so that users need to provide explicitly a `ActionBuilder`).

1) Too much flexibility is kind of confusing, and not that helpful. When i first read the docs I was confused as to what a `ScorerBuilder` was, and how it was related to me just creating a struct with `Component` and `Clone`.
I think it would be much clearer for users to have their scorers-builders/action-builders with explicit `#[derive(ScorerBuilder)]`

This is the exact same argument as: https://github.com/bevyengine/bevy/issues/1843
In theory, it's more flexible to accept any ` std::fmt::Debug + Sync + Send` as a ScorerBuilder (by allowing pre-existing types to be `ScorerBuilders`, but in practice it just makes it less clear, and i believe 99% of users won't use a pre-existing type as a scorer builder)

2) Easy labels. I think right now a user needs to explicitly implement `ScorerBuilder` to have a `Label`.
By forcing all ScorerBuilders to have the explicit type, users could easily add the label via 
```
 `#[derive(ScorerBuilder, label="MyScorer")]`
 pub struct MyScorer;
 ```

**Comment by zkat** [comment]
This is done.
