### ISSUE TITLE
Ability for the Action to modify the Scorer Entity?

### ISSUE THREAD

**Issue by Joey92** [zkat/big-brain#84]
I'm currently trying to make a Scorer that increases its score based on how much a timer has passed:

```rust
#[derive(Debug, Clone, Component, ScorerBuilder)]
pub struct TimePassed(pub Timer);

pub fn timer_scorer_system(
    time: Res<Time>,
    mut query: Query<(&Actor, &mut Score, &mut TimePassed)>,
) {
    for (Actor(actor), mut score, mut timer) in query.iter_mut() {
        if !timer.0.tick(time.delta()).finished() {
            score.set(0.);
            continue;
        }

        score.set(1.);
    }
    return;
}
```

With a repeating timer, the 1 frame it has to set the score to 1 is not enough for the thinker to start the action. And even if so, it would probably just cancel the action immediately due to the score dropping to 0. So in this case I was wondering if i could somehow manage to access the Scorer in the action to reset the timer when the action has finished, but I'm not sure how to do that.

I was thinking of adding the timer to the Actor entity, but I can see Thinkers with multiple TimePassed Scorers, so that does not really work either.

Do you have an idea on how I can accomplish something like this?

**Comment by zkat** [comment]
I would definitely not try to add any extra components to the Scorer or Action entities, tbh (how are you doing that?). What I recommend for stuff like this where you want some level of "stickiness", I suggest having a dedicated entity or component on a regular game entity that keeps track of whether a certain threshold has been crossed, and have your Scorer system observe _that_. For example, you can have an action that toggles the threshold after something has been taken care of.

**Comment by Joey92** [comment]
> I would definitely not try to add any extra components to the Scorer or Action entities, tbh (how are you doing that?)

I'm not. The Scorer has the Components that get added (In this case `TimePassed`) when you add it to the Thinker.

It would help if the Scorer has some kind of link to a spawned Action in the same way as they have access to the Actor. It would have to be an Optional of course, since there isn't an action spawned from the Scorer. In that way the Scorer could observe the ActionState of the spawned action. What do you think about this?

**Comment by zkat** [comment]
This would break down pretty quickly, seeing as not every Action is triggered by a Scorer, and not every Scorer triggers Actions on its own (sometimes there's multiple Scorers). I think this would be a very abstraction-leaky feature.

I don't know where the `TimePassed` component is being added. I'm certainly not adding it myself. But I think the right answer here is that you should use the _Actor's_ `TimePassed` component when evaluating your Scorer and running your Action, instead of trying to reach for the Scorer itself. This is the expected way for Actions to be manipulating game state, and I think it's a relatively simple solution.

**Comment by Joey92** [comment]
> This would break down pretty quickly, seeing as not every Action is triggered by a Scorer, and not every Scorer triggers Actions on its own (sometimes there's multiple Scorers). I think this would be a very abstraction-leaky feature.

I see. I forgot that you can schedule one-off actions that don't originate from a scorer. I'll close the issue since this basically answers my Question.

> I don't know where the `TimePassed` component is being added. I'm certainly not adding it myself.

I'm talking about the component that derives from `ScorerBuilder`. It's being added to the Scorer Entity in the implementation of the Trait, as seen in the example comment: https://github.com/zkat/big-brain/blob/main/src/scorers.rs#L85-L94C8

Sorry if I created any confusion.
